version: '3'

services:
  app:
    image: glitch-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    env_file:
      - .env
    working_dir: /app
    command: npm run dev
