name: Deploy on push

on: [push]  # This will trigger the workflow on every push event to the repository.

jobs:
  build:
    runs-on: self-hosted  # This specifies that the job should run on the self-hosted runner
    if: github.actor == 'Demnu'

    steps:
    - uses: actions/checkout@v2
    - name: Run script
      run: |
        chmod +x ./deploy.sh
        ./deploy.sh

